name: wolfictl-lint
runs:
  using: composite

  steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: wolfi-dev/wolfictl
        path: wolfictl-setup-gha

    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: 'wolfictl-setup-gha/go.mod'
        check-latest: true

    - id: build
      shell: bash
      run: |
        cd wolfictl-setup-gha
        make wolfictl
        mv wolfictl /home/runner/go/bin/
        cd ..
        rm -rf wolfictl-setup-gha
