name: wolfictl-lint
runs:
  using: composite

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: wolfi-dev/wolfictl
        path: wolfictl-setup-gha

    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: 'wolfictl-setup-gha/go.mod'
        check-latest: true

    - id: build
      shell: bash
      run: |
        cd wolfictl-setup-gha
        make wolfictl
        mv wolfictl /home/runner/go/bin/
        cd ..
        rm -rf wolfictl-setup-gha
